---
- name: install softs
  yum:
    name:
      - chrony
      - freeipa-client
    state: present
    update_cache: true

- name: disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: false

- name: disable SElinux
  selinux:
    state: disabled

- name: disable SElinux now
  shell: setenforce 0

- name: Set up timezone
  timezone:
    name: "Europe/Moscow"

- name: enable chrony
  service:
    name: chronyd
    state: restarted
    enabled: true

- name: change /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: add host to ipa-server
  shell: echo -e "yes \n yes" | ipa-client-install --mkhomedir --domain=OTUS.LAN --server=ipa.otus.lan --no-ntp -p admin -w 12345678
